room_all='''SELECT ROOM_NO,CATEGORY,OCCUPANCY FROM ROOMS;'''
room_occupied='''SELECT ROOM_NO,CATEGORY,OCCUPANCY FROM ROOMS WHERE OCCUPANCY IS NOT NULL;'''
room_empty='''SELECT ROOM_NO,CATEGORY,OCCUPANCY FROM ROOMS WHERE OCCUPANCY IS NULL;'''
list_customers = '''SELECT OCCUPANCY FROM ROOMS WHERE OCCUPANCY IS NOT NULL;'''